export const LAUNCH_CHOOSER = 'LAUNCH_CHOOSER';
export const LIST_CHOOSER = 'LIST_CHOOSER';
export const SET_CHOOSER = 'SET_CHOOSER';
export const ADD_COMMAND = 'ADD_COMMAND';
export const DELETE_COMMAND = 'DELETE_COMMAND';
export const SET_COMMAND_LIST = 'SET_COMMAND_LIST';